all:
  children:
    dev:
      hosts:
        ###############################################
        test_gateway:
          # IP address / hostname of the edge gateway
          ansible_host: 18.118.109.190

          # Username that will install services onto the edge gateway
          username: ec2-user
          
          # IP address / hostname of the MQTT broker (typically same as ansible_host)
          mqtt_broker: 18.118.109.190

          # AWS IoT Core endpoint, this can be found from AWS console
          awsiot_endpoint: an6o0flg37eqb-ats.iot.us-east-1.amazonaws.com

          # Location where the x509 certificates can be found, currently stored in an S3 and must be
          # download locally.

          # !!!!!!!!!!!
          # IMPORTANT: Since this variable represents a folder, the trailing '/' IS REQUIRED
          # !!!!!!!!!!!
          x509_src: ~/certs/test/ 

          # Location code for the manufacturing plant
          location: gal

          # Staging location on the edge gateway, this is NOT where code will directly run from
          repo_root: /tmp/staging

          # Set Python version used by Ansible
          ansible_python_interpreter: /usr/bin/python3.8

        ###############################################
        gal_dev_gateway:
          # IP address / hostname of the edge gateway
          ansible_host: 18.118.109.190

          # Username that will install services onto the edge gateway
          username: ec2-user
          
          # IP address / hostname of the MQTT broker (typically same as ansible_host)
          mqtt_broker: gmfgiiot4-eg.pemnet.com

          # AWS IoT Core endpoint, this can be found from AWS console
          awsiot_endpoint: a1mxujejfvl7r9-ats.iot.us-east-1.amazonaws.com

          # Location where the x509 certificates can be found, currently stored in an S3 and must be
          # download locally.

          # !!!!!!!!!!!
          # IMPORTANT: Since this variable represents a folder, the trailing '/' IS REQUIRED
          # !!!!!!!!!!!
          x509_src: ~/certs/gal/

          # Location code for the manufacturing plant
          location: galway

          # Staging location on the edge gateway, this is NOT where code will directly run from
          repo_root: /tmp/staging

          # Set Python version used by Ansible
          ansible_python_interpreter: /usr/bin/python3.8

        ###############################################
        danboro_dev_gateway:
          # IP address / hostname of the edge gateway
          ansible_host: dmfgiiot4-eg.pemnet.com

          # Username that will install services onto the edge gateway
          username: mfink
          
          # IP address / hostname of the MQTT broker (typically same as ansible_host)
          mqtt_broker: dmfgiiot4-eg.pemnet.com

          # AWS IoT Core endpoint, this can be found from AWS console
          awsiot_endpoint: bogusendpoint-abcde-ats.iot.us-east-1.amazonaws.com

          # Location where the x509 certificates can be found, currently stored in an S3 and must be
          # download locally.

          # !!!!!!!!!!!
          # IMPORTANT: Since this variable represents a folder, the trailing '/' IS REQUIRED
          # !!!!!!!!!!!
          x509_src: ~/certs/dan/

          # Location code for the manufacturing plant
          location: dan

          # Staging location on the edge gateway, this is NOT where code will directly run from
          repo_root: /tmp/staging

          # Set Python version used by Ansible
          ansible_python_interpreter: /usr/bin/python3.8

        ###############################################
        coe_dev_gateway:
          # IP address / hostname of the edge gateway
          ansible_host: cmfgiiot4-eg.pemnet.com

          # Username that will install services onto the edge gateway
          username: mfink
          
          # IP address / hostname of the MQTT broker (typically same as ansible_host)
          mqtt_broker: cmfgiiot4-eg.pemnet.com

          # AWS IoT Core endpoint, this can be found from AWS console
          awsiot_endpoint: afgy2u9cufjgl-ats.iot.us-east-1.amazonaws.com

          # Location where the x509 certificates can be found, currently stored in an S3 and must be
          # download locally.

          # !!!!!!!!!!!
          # IMPORTANT: Since this variable represents a folder, the trailing '/' IS REQUIRED
          # !!!!!!!!!!!
          x509_src: ~/certs/coe/

          # Location code for the manufacturing plant
          location: coe

          # Staging location on the edge gateway, this is NOT where code will directly run from
          repo_root: /tmp/staging

          # Set Python version used by Ansible
          ansible_python_interpreter: /usr/bin/python3.8

